_target_: src.models.discriminator.timestepembeddiscriminator.TimestepEmbedDiscriminator
in_channels: ${cfg.channels}
model_channels: 64
num_res_blocks: 2
attention_resolutions: [4]
image_size: ${cfg.image_size}
dropout: 0.0
channel_mult: [1, 2, 2]
conv_resample: true
dims: 2
use_checkpoint: false
num_heads: 4
num_head_channels: 32
use_scale_shift_norm: false